### ISSUE TITLE
Filament v3?

### ISSUE THREAD

**Issue by buchin** [bradyrenting/filament-passwordless#10]
Hi,
Thank you for the great plugin. 
Is there any plan to upgrade this plugin to Filament 3?

**Comment by bradyrenting** [comment]
Hi @buchin,

Thank you for your kind words and for using my plugin! I truly appreciate your support.

I'm glad to hear that you're interested in an update for Filament 3 compatibility. I'm currently working on upgrading the package to support the latest release of Filament. While I can't provide an exact timeline at the moment, I'm working to make the update available as soon as possible.

If you have any further questions or suggestions, please don't hesitate to reach out.

Thanks again!

**Comment by bradyrenting** [comment]
Hey!

I want to provide a transparent update regarding the upgrade to Filament v3. While I genuinely intend to upgrade the plugin and have been thinking about it, unfortunately, I haven't been able to find the time to work on it as of now. Balancing multiple commitments can be challenging, and I hope you understand.

Please know that it's still on my list, and I'm hopeful to get to it as soon as my schedule allows. In the meantime, if anyone has suggestions, contributions, or ideas to share, please don't hesitate to reach out. 🫶

**Comment by buchin** [comment]
Thank you!

**Comment by bradyrenting** [comment]
Thanks to @sWalbrun, this package is now ready for Filament v3!

See: https://github.com/bradyrenting/filament-passwordless/pull/13

**Comment by buchin** [comment]
Oh my goodness. Thank you so much.
